# Generated by Django 5.2.9 on 2026-06-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_token_version_alter_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('kakao', '카카오'), ('google', '구글'), ('apple', '애플')], max_length=20),
        ),
    ]
