# Generated by Codex on 2026-07-06

from django.db import migrations, models


def clamp_existing_reading_settings(apps, schema_editor):
    UserReadingSettings = apps.get_model('accounts', 'UserReadingSettings')
    for settings in UserReadingSettings.objects.all():
        update_fields = []
        if settings.font_size < 14:
            settings.font_size = 14
            update_fields.append('font_size')
        elif settings.font_size > 24:
            settings.font_size = 24
            update_fields.append('font_size')

        if settings.line_height < 1.4:
            settings.line_height = 1.4
            update_fields.append('line_height')
        elif settings.line_height > 2.4:
            settings.line_height = 2.4
            update_fields.append('line_height')

        if update_fields:
            settings.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userreadingsettings_notifications'),
    ]

    operations = [
        migrations.RunPython(clamp_existing_reading_settings, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='userreadingsettings',
            constraint=models.CheckConstraint(
                check=models.Q(font_size__gte=14) & models.Q(font_size__lte=24),
                name='reading_settings_font_size_range',
            ),
        ),
        migrations.AddConstraint(
            model_name='userreadingsettings',
            constraint=models.CheckConstraint(
                check=models.Q(line_height__gte=1.4) & models.Q(line_height__lte=2.4),
                name='reading_settings_line_height_range',
            ),
        ),
    ]
