# Generated by Django 5.2.9 on 2026-09-07 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_admin_member_operations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('bug', 'Bug report'), ('feature', 'Feature request'), ('account', 'Account question'), ('other', 'Other')], max_length=10)),
                ('message', models.TextField(max_length=2000)),
                ('reply_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('received', 'Received')], default='received', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
