# Generated by Django 5.2.9 on 2026-09-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_support_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreadingsettings',
            name='audio_playback_rate',
            field=models.FloatField(default=1.0, help_text='오디오 재생 속도 (0.5-2.0)'),
        ),
        migrations.AddConstraint(
            model_name='userreadingsettings',
            constraint=models.CheckConstraint(condition=models.Q(('audio_playback_rate__gte', 0.5), ('audio_playback_rate__lte', 2.0)), name='reading_settings_audio_rate_range'),
        ),
    ]
