"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9 LTS.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path

from config import security_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _required_env(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        raise ValueError(f"환경변수 {name}가 설정되지 않았습니다.")
    return value


def _required_env_values(names: tuple[str, ...]) -> dict[str, str]:
    values: dict[str, str] = {}
    missing: list[str] = []
    for name in names:
        value = os.environ.get(name)
        if value:
            values[name] = value
        else:
            missing.append(name)

    if missing:
        missing_names = ', '.join(missing)
        raise ValueError(f"환경변수 {missing_names}가 설정되지 않았습니다.")
    return values


_USING_TEST_SETTINGS = os.environ.get('DJANGO_SETTINGS_MODULE') == 'config.test_settings'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _required_env('SECRET_KEY')

CRON_SECRET = os.environ.get('CRON_SECRET') or os.environ.get('HASENA_CRON_SECRET')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ['true', '1', 'yes']

from config.observability import init_sentry_from_env

init_sentry_from_env()

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]
if not ALLOWED_HOSTS:
    # 환경변수 미설정 시: 개발에서는 로컬 호스트, 프로덕션에서는 운영 도메인만 허용
    if DEBUG:
        ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'backend', '192.168.0.41']
    else:
        ALLOWED_HOSTS = ['maeil1dok.app', 'www.maeil1dok.app']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',
    'drf_spectacular',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # Token blacklist for rotation
    'corsheaders',
    'todos',

    # Local apps
    'accounts.apps.AccountsConfig',
    'bible_cache.apps.BibleCacheConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise: gunicorn 등 WSGI 서버에서 정적 파일 직접 서빙 (SecurityMiddleware 바로 뒤)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_DATABASE_ENV = (
    {}
    if _USING_TEST_SETTINGS
    else _required_env_values(('DB_NAME', 'DB_USER', 'DB_PASSWORD', 'DB_HOST'))
)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': _DATABASE_ENV.get('DB_NAME'),
        'USER': _DATABASE_ENV.get('DB_USER'),
        'PASSWORD': _DATABASE_ENV.get('DB_PASSWORD'),
        'HOST': _DATABASE_ENV.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT', '3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.environ.get('STATIC_ROOT', os.path.join(BASE_DIR, 'staticfiles'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = security_settings.CORS_ALLOWED_ORIGINS
CORS_ALLOW_METHODS = security_settings.CORS_ALLOW_METHODS
CORS_ALLOW_HEADERS = security_settings.CORS_ALLOW_HEADERS
CORS_ALLOW_CREDENTIALS = security_settings.CORS_ALLOW_CREDENTIALS
CORS_EXPOSE_HEADERS = security_settings.CORS_EXPOSE_HEADERS
CSRF_COOKIE_HTTPONLY = security_settings.CSRF_COOKIE_HTTPONLY
CSRF_COOKIE_SECURE = security_settings.CSRF_COOKIE_SECURE
CSRF_COOKIE_NAME = security_settings.CSRF_COOKIE_NAME
CSRF_HEADER_NAME = security_settings.CSRF_HEADER_NAME
CSRF_TRUSTED_ORIGINS = security_settings.CSRF_TRUSTED_ORIGINS
COOKIE_SAMESITE = security_settings.COOKIE_SAMESITE
CSRF_COOKIE_SAMESITE = security_settings.CSRF_COOKIE_SAMESITE
SECURE_SSL_REDIRECT = security_settings.SECURE_SSL_REDIRECT
SECURE_PROXY_SSL_HEADER = security_settings.SECURE_PROXY_SSL_HEADER
SESSION_COOKIE_SECURE = security_settings.SESSION_COOKIE_SECURE
SECURE_HSTS_SECONDS = security_settings.SECURE_HSTS_SECONDS
SECURE_HSTS_INCLUDE_SUBDOMAINS = security_settings.SECURE_HSTS_INCLUDE_SUBDOMAINS
SECURE_HSTS_PRELOAD = security_settings.SECURE_HSTS_PRELOAD
SECURE_CONTENT_TYPE_NOSNIFF = security_settings.SECURE_CONTENT_TYPE_NOSNIFF

if security_settings.COOKIE_DOMAIN:
    COOKIE_DOMAIN = security_settings.COOKIE_DOMAIN
    CSRF_COOKIE_DOMAIN = security_settings.COOKIE_DOMAIN

# JWT 설정 추가
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # HttpOnly Cookie 기반 인증 (쿠키 우선, Authorization 헤더 fallback)
        'accounts.authentication.CookieJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'login': '10/min',
        'password_reset': '5/hour',
        'email_verification': '5/hour',
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Maeil1dok API',
    'DESCRIPTION': 'The versioned HTTP contract for the Maeil1dok backend.',
    'VERSION': '1.0.0',
    'OAS_VERSION': '3.0.3',
    'SORT_OPERATIONS': True,
    'SORT_OPERATION_PARAMETERS': True,
    'POSTPROCESSING_HOOKS': [
        'drf_spectacular.hooks.postprocess_schema_enums',
        'config.openapi.normalize_database_integer_ranges',
        'config.openapi.add_router_api_root',
        'config.openapi.mark_duplicate_account_aliases_deprecated',
    ],
}

# JWT 토큰 설정
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),  # 1시간 (보안 강화)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),  # 30일 (상식적인 기간 동안 로그인 유지)
    'ROTATE_REFRESH_TOKENS': True,  # Token refresh 시 새로운 refresh token 발급
    'BLACKLIST_AFTER_ROTATION': True,  # 이전 refresh token 블랙리스트 처리
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# 커스텀 유저 모델 설정
AUTH_USER_MODEL = 'accounts.User'

# 소셜 로그인 설정
KAKAO_CLIENT_ID = os.environ.get('KAKAO_CLIENT_ID')
KAKAO_REDIRECT_URI = os.environ.get('KAKAO_REDIRECT_URI')

GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET') 
GOOGLE_REDIRECT_URI = os.environ.get('GOOGLE_REDIRECT_URI')

APPLE_CLIENT_ID = os.environ.get('APPLE_CLIENT_ID')
APPLE_TEAM_ID = os.environ.get('APPLE_TEAM_ID')
APPLE_KEY_ID = os.environ.get('APPLE_KEY_ID')
APPLE_PRIVATE_KEY = os.environ.get('APPLE_PRIVATE_KEY')

# API.Bible 설정 (히브리어/헬라어/영어 성경)
# https://scripture.api.bible/ 에서 무료 API 키 발급
API_BIBLE_KEY = os.environ.get('API_BIBLE_KEY')

# Google Gemini API 설정 (하세나 영상 AI 요약)
# https://aistudio.google.com/ 에서 무료 API 키 발급
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY')

# YouTube Data API 설정 (플레이리스트 최신 영상 확인)
# Google Cloud Console에서 YouTube Data API v3 활성화 필요
YOUTUBE_API_KEY = os.environ.get('YOUTUBE_API_KEY')

WEB_PUSH_VAPID_PUBLIC_KEY = os.environ.get('WEB_PUSH_VAPID_PUBLIC_KEY', '')
WEB_PUSH_VAPID_PRIVATE_KEY = os.environ.get('WEB_PUSH_VAPID_PRIVATE_KEY', '')
WEB_PUSH_VAPID_SUBJECT = os.environ.get('WEB_PUSH_VAPID_SUBJECT', 'mailto:admin@maeil1dok.app')

# Celery 설정 (비동기 태스크 처리)
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://redis:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Seoul'
CELERY_ENABLE_UTC = False

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', 'redis://redis:6379/1'),
    }
}

# 필수 환경변수 검증
required_env_vars = [
    'KAKAO_CLIENT_ID',
    'KAKAO_REDIRECT_URI',
]

for var in required_env_vars:
    _required_env(var)

# Logging configuration: output all logs to console for Docker
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG' if DEBUG else 'INFO',
    },
}

# Resend 이메일 설정
RESEND_API_KEY = os.environ.get('RESEND_API_KEY')
FROM_EMAIL = os.environ.get('FROM_EMAIL', 'noreply@maeil1dok.app')
FROM_NAME = os.environ.get('FROM_NAME', '매일일독')
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'https://maeil1dok.app')
