# Generated by Django 5.2.9 on 2026-06-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0021_dailybibleschedule_schedule_plan_date_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasenaSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('video_date', models.DateField(blank=True, help_text='영상 날짜', null=True)),
                ('title', models.CharField(blank=True, help_text='영상 제목', max_length=200)),
                ('summary', models.TextField(help_text='AI 생성 요약')),
                ('transcript', models.TextField(blank=True, help_text='원본 자막')),
                ('model_used', models.CharField(default='gemini-2.0-flash', max_length=50)),
                ('is_edited', models.BooleanField(default=False, help_text='관리자가 수정했는지 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '하세나 AI 요약',
                'verbose_name_plural': '하세나 AI 요약',
                'ordering': ['-video_date', '-created_at'],
            },
        ),
    ]
