# Generated by Django 5.2.9 on 2026-06-21 23:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0024_alter_hasenamodel_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reading_reminder', '통독 리마인더'), ('hasena_reminder', '하세나하시조 리마인더'), ('friend_activity', '친구 활동'), ('system', '시스템')], max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(max_length=300)),
                ('target_url', models.CharField(blank=True, max_length=200)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=160)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='todos_notif_recipie_7c4956_idx'), models.Index(fields=['recipient', 'read_at'], name='todos_notif_recipie_c81003_idx'), models.Index(fields=['dedupe_key'], name='todos_notif_dedupe__2c2c27_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('recipient', 'dedupe_key'), name='unique_notification_dedupe_per_user')],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('reading_reminders_enabled', models.BooleanField(default=True)),
                ('hasena_reminders_enabled', models.BooleanField(default=True)),
                ('friend_activity_enabled', models.BooleanField(default=True)),
                ('reading_reminder_time', models.TimeField(default=datetime.time(20, 0))),
                ('hasena_reminder_time', models.TimeField(default=datetime.time(7, 0))),
                ('timezone', models.CharField(default='Asia/Seoul', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '알림 설정',
                'verbose_name_plural': '알림 설정',
                'indexes': [models.Index(fields=['user'], name='todos_notif_user_id_e0d39d_idx'), models.Index(fields=['notifications_enabled', 'reading_reminders_enabled'], name='todos_notif_notific_e32a09_idx'), models.Index(fields=['notifications_enabled', 'hasena_reminders_enabled'], name='todos_notif_notific_23ae41_idx'), models.Index(fields=['notifications_enabled', 'friend_activity_enabled'], name='todos_notif_notific_d5240e_idx')],
            },
        ),
    ]
