# Generated by Django 5.2.9 on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0029_catchup_active_session_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='max_members',
            field=models.IntegerField(default=50, help_text='최대 멤버 수 (1-10000)'),
        ),
    ]
