# Generated by Django 5.2.9 on 2026-09-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0033_notification_settings_absorb_legacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasenaSummaryFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('video_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('error_code', models.CharField(choices=[('transcript_unavailable', 'Transcript unavailable'), ('generation_failed', 'Generation failed'), ('quota_exceeded', 'Quota exceeded'), ('storage_failed', 'Storage failed')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('error_code__in', ['transcript_unavailable', 'generation_failed', 'quota_exceeded', 'storage_failed'])), name='hasena_failure_valid_code')],
            },
        ),
    ]
