# Generated by Django 5.2.9 on 2026-09-20 19:30

import datetime
import django.db.models.deletion
import todos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0034_hasena_summary_failure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NativePushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=16)),
                ('installation_id', models.UUIDField(unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('last_ticket_id', models.CharField(blank=True, max_length=64, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='daily_push_limit',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='paused_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='quiet_hours_end',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='quiet_hours_start',
            field=models.TimeField(default=datetime.time(23, 0)),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='reminder_weekdays',
            field=models.JSONField(default=todos.models.all_reminder_weekdays, help_text='예약 리마인더를 보낼 요일 (0=월요일, 6=일요일)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='streak_reminder_time',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='streak_reminders_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('reading_reminder', '통독 리마인더'), ('hasena_reminder', '하세나하시조 리마인더'), ('streak_reminder', '연속 기록 리마인더'), ('friend_activity', '친구 활동'), ('system', '시스템')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='notificationsettings',
            constraint=models.CheckConstraint(condition=models.Q(('daily_push_limit__gte', 1), ('daily_push_limit__lte', 10)), name='notification_settings_daily_push_limit_range'),
        ),
        migrations.AddField(
            model_name='nativepushsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='native_push_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='nativepushsubscription',
            index=models.Index(fields=['user', 'enabled'], name='native_push_user_enabled_idx'),
        ),
    ]
