# Generated by Django 5.2.9 on 2026-09-20 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0035_contextual_native_push'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NativePushReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=100, unique=True)),
                ('token_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='push_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'push_attempted_at'], name='notification_push_budget_idx'),
        ),
        migrations.AddField(
            model_name='nativepushreceipt',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.notification'),
        ),
        migrations.AddField(
            model_name='nativepushreceipt',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.nativepushsubscription'),
        ),
    ]
