# Generated by Django 5.2.9 on 2026-09-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0037_native_push_opt_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='nativepushreceipt',
            name='subscription_generation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nativepushsubscription',
            name='generation',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
