# Generated by Django 5.2.9 on 2026-08-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEventOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(help_text='Idempotency key. A redelivered event with the same key is ignored.', max_length=64, unique=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('event', models.CharField(choices=[('auth', 'Auth'), ('login', 'Login'), ('refresh_401', 'Refresh 401')], max_length=16)),
                ('method', models.CharField(choices=[('cookie-access-jwt', 'Cookie Access Jwt'), ('header-access-jwt', 'Header Access Jwt'), ('refresh-redemption', 'Refresh Redemption'), ('handoff-code', 'Handoff Code'), ('none', 'None')], max_length=24)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('fail', 'Fail')], max_length=8)),
                ('status', models.PositiveSmallIntegerField()),
                ('route_bucket', models.CharField(choices=[('auth_user', 'Auth User'), ('auth_refresh', 'Auth Refresh'), ('auth_login', 'Auth Login'), ('auth_logout', 'Auth Logout'), ('other', 'Other')], max_length=16)),
                ('cause', models.CharField(blank=True, default='', max_length=32)),
                ('age_bucket', models.CharField(choices=[('lt_30d', 'Lt 30D'), ('gte_30d', 'Gte 30D'), ('unknown', 'Unknown')], default='unknown', max_length=8)),
                ('client', models.CharField(blank=True, default='', max_length=32)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': '인증 이벤트 아웃박스',
                'verbose_name_plural': '인증 이벤트 아웃박스',
                'indexes': [models.Index(fields=['processed_at', 'occurred_at'], name='authmetrics_process_7b334f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthMetricCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('hour', models.PositiveSmallIntegerField(help_text='UTC hour bucket, 0..23.')),
                ('event', models.CharField(choices=[('auth', 'Auth'), ('login', 'Login'), ('refresh_401', 'Refresh 401')], max_length=16)),
                ('method', models.CharField(choices=[('cookie-access-jwt', 'Cookie Access Jwt'), ('header-access-jwt', 'Header Access Jwt'), ('refresh-redemption', 'Refresh Redemption'), ('handoff-code', 'Handoff Code'), ('none', 'None')], max_length=24)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('fail', 'Fail')], max_length=8)),
                ('status', models.PositiveSmallIntegerField()),
                ('route_bucket', models.CharField(choices=[('auth_user', 'Auth User'), ('auth_refresh', 'Auth Refresh'), ('auth_login', 'Auth Login'), ('auth_logout', 'Auth Logout'), ('other', 'Other')], max_length=16)),
                ('cause', models.CharField(blank=True, default='', max_length=32)),
                ('age_bucket', models.CharField(choices=[('lt_30d', 'Lt 30D'), ('gte_30d', 'Gte 30D'), ('unknown', 'Unknown')], max_length=8)),
                ('count', models.PositiveIntegerField(default=0)),
                ('pinned', models.BooleanField(default=False, help_text='Excluded from retention cleanup while true.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '인증 지표 카운터',
                'verbose_name_plural': '인증 지표 카운터',
                'indexes': [models.Index(fields=['day', 'hour'], name='authmetrics_day_f34ebb_idx'), models.Index(fields=['event', 'day'], name='authmetrics_event_228431_idx')],
                'constraints': [models.UniqueConstraint(fields=('day', 'hour', 'event', 'method', 'outcome', 'status', 'route_bucket', 'cause', 'age_bucket'), name='authmetrics_counter_grain_unique')],
            },
        ),
    ]
