# Generated by Django 5.2.9 on 2026-08-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmetrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='authmetriccounter',
            name='authmetrics_counter_grain_unique',
        ),
        migrations.AddField(
            model_name='authmetriccounter',
            name='client',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='authmetriccounter',
            constraint=models.UniqueConstraint(fields=('day', 'hour', 'event', 'method', 'outcome', 'status', 'route_bucket', 'cause', 'age_bucket', 'client'), name='authmetrics_counter_grain_unique'),
        ),
    ]
