export const BIBLE_BOOKS: Record<string, { ko: string; chapters: number }> = {
  gen: { ko: '창세기', chapters: 50 },
  exo: { ko: '출애굽기', chapters: 40 },
  lev: { ko: '레위기', chapters: 27 },
  num: { ko: '민수기', chapters: 36 },
  deu: { ko: '신명기', chapters: 34 },
  jos: { ko: '여호수아', chapters: 24 },
  jdg: { ko: '사사기', chapters: 21 },
  rut: { ko: '룻기', chapters: 4 },
  sa1: { ko: '사무엘상', chapters: 31 },
  sa2: { ko: '사무엘하', chapters: 24 },
  ki1: { ko: '열왕기상', chapters: 22 },
  ki2: { ko: '열왕기하', chapters: 25 },
  ch1: { ko: '역대상', chapters: 29 },
  ch2: { ko: '역대하', chapters: 36 },
  ezr: { ko: '에스라', chapters: 10 },
  neh: { ko: '느헤미야', chapters: 13 },
  est: { ko: '에스더', chapters: 10 },
  job: { ko: '욥기', chapters: 42 },
  psa: { ko: '시편', chapters: 150 },
  pro: { ko: '잠언', chapters: 31 },
  ecc: { ko: '전도서', chapters: 12 },
  sng: { ko: '아가', chapters: 8 },
  isa: { ko: '이사야', chapters: 66 },
  jer: { ko: '예레미야', chapters: 52 },
  lam: { ko: '예레미야애가', chapters: 5 },
  eze: { ko: '에스겔', chapters: 48 },
  dan: { ko: '다니엘', chapters: 12 },
  hos: { ko: '호세아', chapters: 14 },
  joe: { ko: '요엘', chapters: 3 },
  amo: { ko: '아모스', chapters: 9 },
  oba: { ko: '오바댜', chapters: 1 },
  jon: { ko: '요나', chapters: 4 },
  mic: { ko: '미가', chapters: 7 },
  nah: { ko: '나훔', chapters: 3 },
  hab: { ko: '하박국', chapters: 3 },
  zep: { ko: '스바냐', chapters: 3 },
  hag: { ko: '학개', chapters: 2 },
  zec: { ko: '스가랴', chapters: 14 },
  mal: { ko: '말라기', chapters: 4 },
  mat: { ko: '마태복음', chapters: 28 },
  mrk: { ko: '마가복음', chapters: 16 },
  luk: { ko: '누가복음', chapters: 24 },
  jhn: { ko: '요한복음', chapters: 21 },
  act: { ko: '사도행전', chapters: 28 },
  rom: { ko: '로마서', chapters: 16 },
  co1: { ko: '고린도전서', chapters: 16 },
  co2: { ko: '고린도후서', chapters: 13 },
  gal: { ko: '갈라디아서', chapters: 6 },
  eph: { ko: '에베소서', chapters: 6 },
  php: { ko: '빌립보서', chapters: 4 },
  col: { ko: '골로새서', chapters: 4 },
  th1: { ko: '데살로니가전서', chapters: 5 },
  th2: { ko: '데살로니가후서', chapters: 3 },
  ti1: { ko: '디모데전서', chapters: 6 },
  ti2: { ko: '디모데후서', chapters: 4 },
  tit: { ko: '디도서', chapters: 3 },
  phm: { ko: '빌레몬서', chapters: 1 },
  heb: { ko: '히브리서', chapters: 13 },
  jam: { ko: '야고보서', chapters: 5 },
  pe1: { ko: '베드로전서', chapters: 5 },
  pe2: { ko: '베드로후서', chapters: 3 },
  jo1: { ko: '요한1서', chapters: 5 },
  jo2: { ko: '요한2서', chapters: 1 },
  jo3: { ko: '요한3서', chapters: 1 },
  jud: { ko: '유다서', chapters: 1 },
  rev: { ko: '요한계시록', chapters: 22 },
}

export const BIBLE_VERSIONS = {
  GAE: '개역개정',
  KNT: '새한글',
  HAN: '한글KJV',
  SAE: '새번역',
  SAENEW: '새번역개정',
  COG: '공동번역',
  COGNEW: '공동번역개정',
} as const

export type BibleVersion = keyof typeof BIBLE_VERSIONS

export const BIBLE_BOOK_KEYS = Object.keys(BIBLE_BOOKS)

export function isBibleVersion(value: string): value is BibleVersion {
  return value in BIBLE_VERSIONS
}
